### ISSUE TITLE
Feedback HIIT 1.0.2

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [ATryder/HIIT#1]
The New icon looks nice.

will there also be a possibility to enter exercises later? because with start and stop i don't know what i'm practising.

**Comment by ATryder** [comment]
Yeah I'll probably add more functionality at some point and I'll keep your suggestion in mind. I can't say when that'll be though.

**Comment by mondlicht-und-sterne** [comment]
because programmers don't have time ;) at least that's what they often say.

**Comment by ATryder** [comment]
Well I have another project that I'm working on. I'm sure I'll take a break from it to fix up my other projects at some point, but that could be anywhere from later today to late next year. 🤷

**Comment by mondlicht-und-sterne** [comment]
why do they release an app that can't do anything, or let's say I can turn a stopwatch on and off. because it's one with a nice icon?

**Comment by ATryder** [comment]
> why do they release an app...

Who are they?
